theme: jekyll-theme-minimal
title: Welcome to SlapFrog Labs
Description: From the Minds of Morons
owner:
  name: StevieD
  avatar: avi.jpg
  bio: "Entrepreneur, Triathlete, Yogi, Geek"
  email: slapfrog@danlargo.com
  # Do not include the @ symbol in your Twitter username
  twitter: slapfroglabs
  linkedin: danlargo
  github: danlargo


![Logo](/images/frog 240.jpg)
