theme: jekyll-theme-minimal
title: Welcome to SlapFrog Labs
Description: Come back soon for more content

owner:
  name: StevieD
  avatar: avi.jpg
  bio: "Entrepreneur, Triathlete, Yogi, Geek"
  email: danlargo01@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: danlargo
  linkedin: danlargo
  github: danlargo
